In [ ]:
# This script checks if a specified folder exists and lists all CSV files in that folder.
from pathlib import Path

data_folder = Path(r"C:\Users\DELL\Desktop\Data Analytics\Project\Dataset")

print("Folder exists:", data_folder.exists())
print("CSV files:", [file.name for file in data_folder.glob("*.csv")])

Folder exists: True
CSV files: ['2019-Dec.csv', '2019-Nov.csv', '2019-Oct.csv', '2020-Feb.csv', '2020-Jan.csv']

In [2]:
# List all CSV files with their sizes
for file in sorted(data_folder.glob("*.csv")):
    size_mb = file.stat().st_size / (1024 * 1024)
    print(file.name, f"{size_mb: .1f} MB)")

2019-Dec.csv  396.1 MB)
2019-Nov.csv  520.6 MB)
2019-Oct.csv  460.2 MB)
2020-Feb.csv  466.2 MB)
2020-Jan.csv  478.5 MB)

In [3]:
# List all CSV files with their column names
import pandas as pd
for file in sorted(data_folder.glob("*.csv")):
    columns = pd.read_csv(file, nrows=0).columns.tolist()
    print(file.name, columns)

2019-Dec.csv ['event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']
2019-Nov.csv ['event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']
2019-Oct.csv ['event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']
2020-Feb.csv ['event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']
2020-Jan.csv ['event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']

In [4]:
# Count the number of rows in each CSV file
chunk_size = 500_000

for file in sorted(data_folder.glob("*.csv")):
    row_count = 0

    for chunk in pd.read_csv(file, chunksize=chunk_size):
        row_count += len(chunk)

    print(file.name, f"{row_count:,} rows")

2019-Dec.csv 3,533,286 rows
2019-Nov.csv 4,635,837 rows
2019-Oct.csv 4,102,283 rows
2020-Feb.csv 4,156,682 rows
2020-Jan.csv 4,264,752 rows

In [5]:
# Count the number of missing values in each CSV file
missing_totals = {}

for file in sorted(data_folder.glob("*.csv")):
    file_missing = {}

    for chunk in pd.read_csv(file, chunksize=chunk_size):
        missing_in_chunk = chunk.isna().sum()

        for column, count in missing_in_chunk.items():
            file_missing[column] = file_missing.get(column, 0) + count

    missing_totals[file.name] = file_missing

In [6]:
# Print the missing values for each file
for file_name, counts in missing_totals.items():
    print(f"\n{file_name}")
    for column, count in counts.items():
        print(f"{column}: {count:,}")

2019-Dec.csv
event_time: 0
event_type: 0
product_id: 0
category_id: 0
category_code: 3,474,821
brand: 1,510,289
price: 0
user_id: 0
user_session: 779

2019-Nov.csv
event_time: 0
event_type: 0
product_id: 0
category_id: 0
category_code: 4,560,089
brand: 1,986,029
price: 0
user_id: 0
user_session: 813

2019-Oct.csv
event_time: 0
event_type: 0
product_id: 0
category_id: 0
category_code: 4,034,806
brand: 1,659,261
price: 0
user_id: 0
user_session: 637

2020-Feb.csv
event_time: 0
event_type: 0
product_id: 0
category_id: 0
category_code: 4,079,497
brand: 1,825,908
price: 0
user_id: 0
user_session: 1,055

2020-Jan.csv
event_time: 0
event_type: 0
product_id: 0
category_id: 0
category_code: 4,190,033
brand: 1,775,630
price: 0
user_id: 0
user_session: 1,314

In [7]:
# Count the number of occurrences of each event type in each CSV file
event_totals = {}

for file in sorted(data_folder.glob("*.csv")):
    file_events = {}

    for chunk in pd.read_csv(
        file,
        usecols=["event_type"],
        chunksize=chunk_size
    ):
        event_counts = chunk["event_type"].value_counts()

        for event, count in event_counts.items():
            file_events[event] = file_events.get(event, 0) + count

    event_totals[file.name] = file_events

for file_name, counts in event_totals.items():
    print(f"\n{file_name}")
    for event, count in counts.items():
        print(f"  {event}: {count:,}")

2019-Dec.csv
  view: 1,728,331
  cart: 927,124
  remove_from_cart: 664,655
  purchase: 213,176

2019-Nov.csv
  view: 2,076,132
  cart: 1,311,807
  remove_from_cart: 925,481
  purchase: 322,417

2019-Oct.csv
  view: 1,862,164
  cart: 1,232,385
  remove_from_cart: 762,110
  purchase: 245,624

2020-Feb.csv
  view: 1,953,586
  cart: 1,148,694
  remove_from_cart: 812,409
  purchase: 241,993

2020-Jan.csv
  view: 2,037,608
  cart: 1,148,323
  remove_from_cart: 815,024
  purchase: 263,797

In [ ]:
october_file = data_folder / "2019-Oct.csv"

print(october_file.exists())

True

In [ ]:
import pandas as pd 

october_file = data_folder / "2019-Oct.csv"
sample = pd.read_csv(october_file, nrows=5)

print(sample.shape)
print(sample.columns.tolist())
sample

(5, 9)
['event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,cart,5773203,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
1,2019-10-01 00:00:03 UTC,cart,5773353,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
2,2019-10-01 00:00:07 UTC,cart,5881589,2151191071051219817,NaN,lovely,13.48,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
3,2019-10-01 00:00:07 UTC,cart,5723490,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
4,2019-10-01 00:00:15 UTC,cart,5881449,1487580013522845895,NaN,lovely,0.56,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9

In [ ]:
small_sample = pd.read_csv(october_file, nrows=5)

small_sample["price"]

0     2.62
1     2.62
2    13.48
3     2.62
4     0.56
Name: price, dtype: float64

In [5]:
price_sample = pd.read_csv(october_file, nrows=10_000)

print("Negative prices:", (price_sample["price"] < 0).sum())
print("Zero prices:", (price_sample["price"] == 0).sum())

Negative prices: 0
Zero prices: 8

In [6]:
zero_price_rows = price_sample[price_sample["price"] == 0]

zero_price_rows[["event_time", "event_type", "product_id", "price"]]

                   event_time event_type  product_id  price
2454  2019-10-01 02:05:17 UTC       view     5892084    0.0
2614  2019-10-01 02:15:41 UTC       view     5892052    0.0
5686  2019-10-01 04:25:00 UTC       view     5873432    0.0
6086  2019-10-01 04:33:15 UTC       view     5882605    0.0
8344  2019-10-01 05:16:30 UTC       view     5889621    0.0
8417  2019-10-01 05:18:03 UTC       view     5889622    0.0
8465  2019-10-01 05:18:46 UTC       view     5889623    0.0
8950  2019-10-01 05:24:38 UTC       view     5873431    0.0

In [7]:
october_prices = pd.read_csv(october_file, usecols=["price"])

print("Rows checked:", len(october_prices))
print("Zero prices:", (october_prices["price"] == 0).sum())
print("Negative prices:", (october_prices["price"] < 0).sum())

Rows checked: 4102283
Zero prices: 6066
Negative prices: 20

In [8]:
price_events = pd.read_csv(
    october_file,
    usecols=["price", "event_type"]
)

negative_price_rows = price_events[price_events["price"] < 0]

negative_price_rows["event_type"].value_counts()

event_type
purchase    20
Name: count, dtype: int64

In [9]:
purchase_details = pd.read_csv(
    october_file,
    usecols=["event_time", "event_type", "product_id", "price"]
)

negative_purchases = purchase_details[purchase_details["price"] < 0]

negative_purchases

                      event_time event_type  product_id  price
112860   2019-10-01 19:10:56 UTC   purchase     5716857 -23.81
198302   2019-10-02 08:30:03 UTC   purchase     5716855  -7.94
436918   2019-10-03 17:37:04 UTC   purchase     5716859 -47.62
443204   2019-10-03 18:25:39 UTC   purchase     5670257 -15.87
1295556  2019-10-09 14:49:14 UTC   purchase     5716855  -7.94
1426186  2019-10-10 14:33:29 UTC   purchase     5716855  -7.94
1519246  2019-10-11 10:27:19 UTC   purchase     5716859 -47.62
1783312  2019-10-13 16:46:01 UTC   purchase     5716857 -23.81
1924072  2019-10-14 17:33:24 UTC   purchase     5716861 -79.37
2143762  2019-10-16 11:41:06 UTC   purchase     5716857 -23.81
2286569  2019-10-17 11:41:07 UTC   purchase     5670257 -15.87
2418566  2019-10-18 12:27:23 UTC   purchase     5670257 -15.87
3056821  2019-10-23 15:11:37 UTC   purchase     5670257 -15.87
3135434  2019-10-24 08:10:06 UTC   purchase     5716859 -47.62
3502423  2019-10-27 11:24:32 UTC   purchase     5716859 -47.62
3593034  2019-10-28 04:19:20 UTC   purchase     5670257 -15.87
3608726  2019-10-28 07:41:54 UTC   purchase     5716857 -23.81
3670216  2019-10-28 15:43:59 UTC   purchase     5670257 -15.87
3798007  2019-10-29 14:34:24 UTC   purchase     5716857 -23.81
3807737  2019-10-29 16:07:23 UTC   purchase     5716859 -47.62

In [10]:
purchase_details.dtypes

event_time        str
event_type        str
product_id      int64
price         float64
dtype: object

In [11]:
purchase_details["event_time"] = pd.to_datetime(
    purchase_details["event_time"],
    utc=True
)

purchase_details.dtypes

event_time    datetime64[us, UTC]
event_type                    str
product_id                  int64
price                     float64
dtype: object

In [12]:
october_sample = pd.read_csv(october_file, nrows=10_000)

october_sample.duplicated().sum()

np.int64(543)

In [13]:
duplicate_rows = october_sample[october_sample.duplicated(keep=False)]

duplicate_rows.head(10)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
12,2019-10-01 00:00:30 UTC,remove_from_cart,5809103,1487580013522845895,NaN,irisk,0.60,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
13,2019-10-01 00:00:30 UTC,remove_from_cart,5809103,1487580013522845895,NaN,irisk,0.60,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
29,2019-10-01 00:01:05 UTC,remove_from_cart,5858981,1487580007634043851,NaN,de.lux,0.79,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
30,2019-10-01 00:01:05 UTC,remove_from_cart,5858981,1487580007634043851,NaN,de.lux,0.79,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
34,2019-10-01 00:01:07 UTC,remove_from_cart,5312,1487580009471148064,NaN,runail,1.27,467916806,2f5b5546-b8cb-9ee7-7ecd-84276f8ef486
36,2019-10-01 00:01:07 UTC,remove_from_cart,5312,1487580009471148064,NaN,runail,1.27,467916806,2f5b5546-b8cb-9ee7-7ecd-84276f8ef486
37,2019-10-01 00:01:10 UTC,remove_from_cart,5823915,1487580007432717250,NaN,milv,1.59,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
38,2019-10-01 00:01:10 UTC,remove_from_cart,5823915,1487580007432717250,NaN,milv,1.59,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
50,2019-10-01 00:01:24 UTC,remove_from_cart,5664641,1487580011425693811,NaN,NaN,0.70,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
51,2019-10-01 00:01:24 UTC,remove_from_cart,5664641,1487580011425693811,NaN,NaN,0.70,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9

In [14]:
duplicate_rows["event_type"].value_counts()

event_type
remove_from_cart    1010
cart                  66
Name: count, dtype: int64

In [15]:
sample_without_duplicates = october_sample.drop_duplicates()

print("Rows in original sample:", len(october_sample))
print("Rows after removing exact repeats:", len(sample_without_duplicates))

Rows in original sample: 10000
Rows after removing exact repeats: 9457

In [16]:
print("Before removing exact repeats:")
print(october_sample["event_type"].value_counts())

print("\nAfter removing exact repeats:")
print(sample_without_duplicates["event_type"].value_counts())

Before removing exact repeats:
event_type
view                4252
cart                2939
remove_from_cart    1987
purchase             822
Name: count, dtype: int64

After removing exact repeats:
event_type
view                4252
cart                2903
remove_from_cart    1480
purchase             822
Name: count, dtype: int64

In [17]:
cart_rows_before = october_sample[october_sample["event_type"] == "cart"]
cart_rows_after = sample_without_duplicates[
    sample_without_duplicates["event_type"] == "cart"
]

print("Cart sessions before:", cart_rows_before["user_session"].nunique())
print("Cart sessions after:", cart_rows_after["user_session"].nunique())

Cart sessions before: 478
Cart sessions after: 478

In [18]:
october_sessions = pd.read_csv(
    october_file,
    usecols=["user_session"]
)

october_sessions["user_session"].isna().sum()

np.int64(637)

In [19]:
missing_session_percent = (
    october_sessions["user_session"].isna().sum()
    / len(october_sessions)
    * 100
)

print(f"{missing_session_percent:.4f}%")

0.0155%

In [20]:
october_clean_sample = october_sample.copy()

october_clean_sample["event_time"] = pd.to_datetime(
    october_clean_sample["event_time"],
    utc=True
)

print("Rows before:", len(october_sample))
print("Rows after:", len(october_clean_sample))
print("Event time type:", october_clean_sample["event_time"].dtype)

Rows before: 10000
Rows after: 10000
Event time type: datetime64[us, UTC]

In [21]:
october_clean_sample["event_type"] = october_clean_sample["event_type"].str.strip()
october_clean_sample["category_code"] = october_clean_sample["category_code"].str.strip()
october_clean_sample["brand"] = october_clean_sample["brand"].str.strip()
october_clean_sample["user_session"] = october_clean_sample["user_session"].str.strip()

october_clean_sample[["event_type", "category_code", "brand", "user_session"]].head()

  event_type category_code   brand                          user_session
0       cart           NaN  runail  26dd6e6e-4dac-4778-8d2c-92e149dab885
1       cart           NaN  runail  26dd6e6e-4dac-4778-8d2c-92e149dab885
2       cart           NaN  lovely  49e8d843-adf3-428b-a2c3-fe8bc6a307c9
3       cart           NaN  runail  26dd6e6e-4dac-4778-8d2c-92e149dab885
4       cart           NaN  lovely  49e8d843-adf3-428b-a2c3-fe8bc6a307c9

In [22]:
october_clean_sample.isna().sum()

event_time          0
event_type          0
product_id          0
category_id         0
category_code    9765
brand            3840
price               0
user_id             0
user_session        0
dtype: int64

In [23]:
cleaned_folder = data_folder.parent / "Cleaned_Data"
cleaned_folder.mkdir(exist_ok=True)

print(cleaned_folder)

C:\Users\DELL\Desktop\Data Analytics\Project\Cleaned_Data

In [24]:
october_chunks = pd.read_csv(october_file, chunksize=500_000)
first_chunk = next(october_chunks)

print(first_chunk.shape)

(500000, 9)

In [25]:
cleaned_first_chunk = first_chunk.copy()

cleaned_first_chunk["event_time"] = pd.to_datetime(
    cleaned_first_chunk["event_time"],
    utc=True
)

cleaned_first_chunk["event_type"] = cleaned_first_chunk["event_type"].str.strip()
cleaned_first_chunk["category_code"] = cleaned_first_chunk["category_code"].str.strip()
cleaned_first_chunk["brand"] = cleaned_first_chunk["brand"].str.strip()
cleaned_first_chunk["user_session"] = cleaned_first_chunk["user_session"].str.strip()

print("Rows:", len(cleaned_first_chunk))
print(cleaned_first_chunk.dtypes)

Rows: 500000
event_time       datetime64[us, UTC]
event_type                       str
product_id                     int64
category_id                    int64
category_code                    str
brand                            str
price                        float64
user_id                        int64
user_session                     str
dtype: object

In [26]:
october_output = cleaned_folder / "2019-Oct_cleaned.csv"

first_chunk = True
rows_written = 0

for chunk in pd.read_csv(october_file, chunksize=500_000):
    chunk["event_time"] = pd.to_datetime(chunk["event_time"], utc=True)

    chunk["event_type"] = chunk["event_type"].str.strip()
    chunk["category_code"] = chunk["category_code"].str.strip()
    chunk["brand"] = chunk["brand"].str.strip()
    chunk["user_session"] = chunk["user_session"].str.strip()

    chunk.to_csv(
        october_output,
        mode="w" if first_chunk else "a",
        index=False,
        header=first_chunk
    )

    rows_written += len(chunk)
    print(f"Processed {rows_written:,} rows")

    first_chunk = False

print("Saved cleaned file:", october_output)

Processed 500,000 rows
Processed 1,000,000 rows
Processed 1,500,000 rows
Processed 2,000,000 rows
Processed 2,500,000 rows
Processed 3,000,000 rows
Processed 3,500,000 rows
Processed 4,000,000 rows
Processed 4,102,283 rows
Saved cleaned file: C:\Users\DELL\Desktop\Data Analytics\Project\Cleaned_Data\2019-Oct_cleaned.csv

In [27]:
cleaned_row_count = 0

for chunk in pd.read_csv(october_output, chunksize=500_000):
    cleaned_row_count += len(chunk)

print("Rows written:", rows_written)
print("Rows found in saved file:", cleaned_row_count)

Rows written: 4102283
Rows found in saved file: 4102283

In [28]:
input_file = data_folder / "2019-Nov.csv"
output_file = cleaned_folder / "2019-Nov_cleaned.csv"

first_chunk = True
rows_written = 0

for chunk in pd.read_csv(input_file, chunksize=500_000):
    chunk["event_time"] = pd.to_datetime(chunk["event_time"], utc=True)

    chunk["event_type"] = chunk["event_type"].str.strip()
    chunk["category_code"] = chunk["category_code"].str.strip()
    chunk["brand"] = chunk["brand"].str.strip()
    chunk["user_session"] = chunk["user_session"].str.strip()

    chunk.to_csv(
        output_file,
        mode="w" if first_chunk else "a",
        index=False,
        header=first_chunk
    )

    rows_written += len(chunk)
    print(f"Processed {rows_written:,} rows")

    first_chunk = False

print("Saved cleaned file:", output_file)

Processed 500,000 rows
Processed 1,000,000 rows
Processed 1,500,000 rows
Processed 2,000,000 rows
Processed 2,500,000 rows
Processed 3,000,000 rows
Processed 3,500,000 rows
Processed 4,000,000 rows
Processed 4,500,000 rows
Processed 4,635,837 rows
Saved cleaned file: C:\Users\DELL\Desktop\Data Analytics\Project\Cleaned_Data\2019-Nov_cleaned.csv

In [29]:
input_file = data_folder / "2019-Dec.csv"
output_file = cleaned_folder / "2019-Dec_cleaned.csv"

first_chunk = True
rows_written = 0

for chunk in pd.read_csv(input_file, chunksize=500_000):
    chunk["event_time"] = pd.to_datetime(chunk["event_time"], utc=True)

    chunk["event_type"] = chunk["event_type"].str.strip()
    chunk["category_code"] = chunk["category_code"].str.strip()
    chunk["brand"] = chunk["brand"].str.strip()
    chunk["user_session"] = chunk["user_session"].str.strip()

    chunk.to_csv(
        output_file,
        mode="w" if first_chunk else "a",
        index=False,
        header=first_chunk
    )

    rows_written += len(chunk)
    print(f"Processed {rows_written:,} rows")

    first_chunk = False

print("Saved cleaned file:", output_file)

Processed 500,000 rows
Processed 1,000,000 rows
Processed 1,500,000 rows
Processed 2,000,000 rows
Processed 2,500,000 rows
Processed 3,000,000 rows
Processed 3,500,000 rows
Processed 3,533,286 rows
Saved cleaned file: C:\Users\DELL\Desktop\Data Analytics\Project\Cleaned_Data\2019-Dec_cleaned.csv

In [3]:
input_file = data_folder / "2020-Jan.csv"
output_file = cleaned_folder / "2020-Jan_cleaned.csv"

first_chunk = True
rows_written = 0

for chunk in pd.read_csv(input_file, chunksize=500_000):
    chunk["event_time"] = pd.to_datetime(chunk["event_time"], utc=True)

    chunk["event_type"] = chunk["event_type"].str.strip()
    chunk["category_code"] = chunk["category_code"].str.strip()
    chunk["brand"] = chunk["brand"].str.strip()
    chunk["user_session"] = chunk["user_session"].str.strip()

    chunk.to_csv(
        output_file,
        mode="w" if first_chunk else "a",
        index=False,
        header=first_chunk
    )

    rows_written += len(chunk)
    print(f"Processed {rows_written:,} rows")

    first_chunk = False

print("Saved cleaned file:", output_file)

Processed 500,000 rows
Processed 1,000,000 rows
Processed 1,500,000 rows
Processed 2,000,000 rows
Processed 2,500,000 rows
Processed 3,000,000 rows
Processed 3,500,000 rows
Processed 4,000,000 rows
Processed 4,264,752 rows
Saved cleaned file: C:\Users\DELL\Desktop\Data Analytics\Project\Cleaned_Data\2020-Jan_cleaned.csv

In [2]:
from pathlib import Path
import pandas as pd

data_folder = Path(r"C:\Users\DELL\Desktop\Data Analytics\Project\Dataset")
cleaned_folder = data_folder.parent / "Cleaned_Data"
cleaned_folder.mkdir(exist_ok=True)

In [4]:
input_file = data_folder / "2020-Feb.csv"
output_file = cleaned_folder / "2020-Feb_cleaned.csv"

first_chunk = True
rows_written = 0

for chunk in pd.read_csv(input_file, chunksize=500_000):
    chunk["event_time"] = pd.to_datetime(chunk["event_time"], utc=True)

    chunk["event_type"] = chunk["event_type"].str.strip()
    chunk["category_code"] = chunk["category_code"].str.strip()
    chunk["brand"] = chunk["brand"].str.strip()
    chunk["user_session"] = chunk["user_session"].str.strip()

    chunk.to_csv(
        output_file,
        mode="w" if first_chunk else "a",
        index=False,
        header=first_chunk
    )

    rows_written += len(chunk)
    print(f"Processed {rows_written:,} rows")

    first_chunk = False

print("Saved cleaned file:", output_file)

Processed 500,000 rows
Processed 1,000,000 rows
Processed 1,500,000 rows
Processed 2,000,000 rows
Processed 2,500,000 rows
Processed 3,000,000 rows
Processed 3,500,000 rows
Processed 4,000,000 rows
Processed 4,156,682 rows
Saved cleaned file: C:\Users\DELL\Desktop\Data Analytics\Project\Cleaned_Data\2020-Feb_cleaned.csv

In [5]:
total_cleaned_rows = 0

for file in sorted(cleaned_folder.glob("*_cleaned.csv")):
    file_rows = 0

    for chunk in pd.read_csv(file, chunksize=500_000):
        file_rows += len(chunk)

    print(file.name, f"{file_rows:,} rows")
    total_cleaned_rows += file_rows

print("Total cleaned rows:", f"{total_cleaned_rows:,}")

2019-Dec_cleaned.csv 3,533,286 rows
2019-Nov_cleaned.csv 4,635,837 rows
2019-Oct_cleaned.csv 4,102,283 rows
2020-Feb_cleaned.csv 4,156,682 rows
2020-Jan_cleaned.csv 4,264,752 rows
Total cleaned rows: 20,692,840

In [6]:
october_cleaned_preview = pd.read_csv(
    cleaned_folder / "2019-Oct_cleaned.csv",
    nrows=5,
    parse_dates=["event_time"]
)

print(october_cleaned_preview.shape)
print(october_cleaned_preview.columns.tolist())
print(october_cleaned_preview["event_time"].dtype)

(5, 9)
['event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']
datetime64[us, UTC]

In [7]:
cleaning_log = pd.DataFrame({
    "file": [
        "2019-Oct.csv",
        "2019-Nov.csv",
        "2019-Dec.csv",
        "2020-Jan.csv",
        "2020-Feb.csv"
    ],
    "rows_before": [
        4_102_283,
        4_635_837,
        3_533_286,
        4_264_752,
        4_156_682
    ],
    "rows_after": [
        4_102_283,
        4_635_837,
        3_533_286,
        4_264_752,
        4_156_682
    ],
    "rows_removed": [0, 0, 0, 0, 0]
})

cleaning_log

           file  rows_before  rows_after  rows_removed
0  2019-Oct.csv      4102283     4102283             0
1  2019-Nov.csv      4635837     4635837             0
2  2019-Dec.csv      3533286     3533286             0
3  2020-Jan.csv      4264752     4264752             0
4  2020-Feb.csv      4156682     4156682             0

In [8]:
cleaning_log["actions_applied"] = (
    "Converted event_time to UTC and trimmed text columns"
)

cleaning_log["issues_preserved"] = (
    "Kept missing values, unusual prices, and exact repeated rows; "
    "no records removed"
)

cleaning_log

,file,rows_before,rows_after,rows_removed,actions_applied,issues_preserved
0,2019-Oct.csv,4102283,4102283,0,Converted event_time to UTC and trimmed text c...,"Kept missing values, unusual prices, and exact..."
1,2019-Nov.csv,4635837,4635837,0,Converted event_time to UTC and trimmed text c...,"Kept missing values, unusual prices, and exact..."
2,2019-Dec.csv,3533286,3533286,0,Converted event_time to UTC and trimmed text c...,"Kept missing values, unusual prices, and exact..."
3,2020-Jan.csv,4264752,4264752,0,Converted event_time to UTC and trimmed text c...,"Kept missing values, unusual prices, and exact..."
4,2020-Feb.csv,4156682,4156682,0,Converted event_time to UTC and trimmed text c...,"Kept missing values, unusual prices, and exact..."

In [9]:
cleaning_log["issues_preserved"] = (
    "Missing values and unusual prices kept; exact repeats not removed. "
    "Duplicate check covered only the first 10,000 October rows."
)

log_file = cleaned_folder / "cleaning_log.csv"
cleaning_log.to_csv(log_file, index=False)

print("Cleaning log saved to:", log_file)

Cleaning log saved to: C:\Users\DELL\Desktop\Data Analytics\Project\Cleaned_Data\cleaning_log.csv

In [10]:
saved_log = pd.read_csv(log_file)
saved_log

,file,rows_before,rows_after,rows_removed,actions_applied,issues_preserved
0,2019-Oct.csv,4102283,4102283,0,Converted event_time to UTC and trimmed text c...,Missing values and unusual prices kept; exact ...
1,2019-Nov.csv,4635837,4635837,0,Converted event_time to UTC and trimmed text c...,Missing values and unusual prices kept; exact ...
2,2019-Dec.csv,3533286,3533286,0,Converted event_time to UTC and trimmed text c...,Missing values and unusual prices kept; exact ...
3,2020-Jan.csv,4264752,4264752,0,Converted event_time to UTC and trimmed text c...,Missing values and unusual prices kept; exact ...
4,2020-Feb.csv,4156682,4156682,0,Converted event_time to UTC and trimmed text c...,Missing values and unusual prices kept; exact ...

In [11]:
october_file = cleaned_folder / "2019-Oct_cleaned.csv"
sample = pd.read_csv(october_file, nrows=5)

sample[["event_time"]]

                  event_time
0  2019-10-01 00:00:00+00:00
1  2019-10-01 00:00:03+00:00
2  2019-10-01 00:00:07+00:00
3  2019-10-01 00:00:07+00:00
4  2019-10-01 00:00:15+00:00

In [12]:
sample[["event_type"]]

  event_type
0       cart
1       cart
2       cart
3       cart
4       cart

In [13]:
sample[["product_id"]]

   product_id
0     5773203
1     5773353
2     5881589
3     5723490
4     5881449

In [14]:
sample[["category_id"]]

           category_id
0  1487580005134238553
1  1487580005134238553
2  2151191071051219817
3  1487580005134238553
4  1487580013522845895

In [15]:
sample[["category_code"]]

   category_code
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN

In [16]:
sample_with_category = pd.read_csv(
    october_file,
    usecols=["category_code"],
    nrows=1000
)

sample_with_category["category_code"].dropna().head()

21     appliances.environment.vacuum
264              stationery.cartrige
269              stationery.cartrige
274              stationery.cartrige
276              stationery.cartrige
Name: category_code, dtype: str

In [17]:
sample[["brand"]]

    brand
0  runail
1  runail
2  lovely
3  runail
4  lovely

In [18]:
sample[["price"]]

   price
0   2.62
1   2.62
2  13.48
3   2.62
4   0.56

In [19]:
sample[["user_id"]]

     user_id
0  463240011
1  463240011
2  429681830
3  463240011
4  429681830

In [20]:
sample[["user_session"]]

                           user_session
0  26dd6e6e-4dac-4778-8d2c-92e149dab885
1  26dd6e6e-4dac-4778-8d2c-92e149dab885
2  49e8d843-adf3-428b-a2c3-fe8bc6a307c9
3  26dd6e6e-4dac-4778-8d2c-92e149dab885
4  49e8d843-adf3-428b-a2c3-fe8bc6a307c9

In [21]:
data_dictionary = pd.DataFrame([
    {
        "column": "event_time",
        "meaning": "Date and time when the customer activity occurred",
        "data_type": "Date/time (UTC)",
        "example": "2019-10-01 00:00:03+00:00",
        "notes": "Timestamp is recorded in UTC"
    },
    {
        "column": "event_type",
        "meaning": "Type of customer activity recorded",
        "data_type": "Text (category)",
        "example": "cart",
        "notes": "Values include view, cart, remove_from_cart, and purchase"
    },
    {
        "column": "product_id",
        "meaning": "Identifier of the product involved in the event",
        "data_type": "Whole number (ID)",
        "example": "5773203",
        "notes": "An identifier, not a quantity"
    },
    {
        "column": "category_id",
        "meaning": "Identifier of the category the product belongs to",
        "data_type": "Whole number (ID)",
        "example": "1487580005134238553",
        "notes": "An identifier, not a quantity"
    },
    {
        "column": "category_code",
        "meaning": "Text label describing the product category or subcategory",
        "data_type": "Text (category)",
        "example": "appliances.environment.vacuum",
        "notes": "Many values are missing; periods separate category levels"
    },
    {
        "column": "brand",
        "meaning": "Brand associated with the product",
        "data_type": "Text (category)",
        "example": "runail",
        "notes": "Some values are missing"
    },
    {
        "column": "price",
        "meaning": "Recorded price of the product involved in the event",
        "data_type": "Decimal number",
        "example": "2.62",
        "notes": "Zero and negative values occur; retained for review"
    },
    {
        "column": "user_id",
        "meaning": "Identifier of the user associated with the event",
        "data_type": "Whole number (ID)",
        "example": "463240011",
        "notes": "An identifier, not a quantity"
    },
    {
        "column": "user_session",
        "meaning": "Identifier for a browsing session",
        "data_type": "Text (ID)",
        "example": "26dd6e6e-4dac-4778-8d2c-92e149dab885",
        "notes": "Repeats across events in a session; missing values cannot be used for session-based KPIs"
    }
])

data_dictionary

,column,meaning,data_type,example,notes
0,event_time,Date and time when the customer activity occurred,Date/time (UTC),2019-10-01 00:00:03+00:00,Timestamp is recorded in UTC
1,event_type,Type of customer activity recorded,Text (category),cart,"Values include view, cart, remove_from_cart, a..."
2,product_id,Identifier of the product involved in the event,Whole number (ID),5773203,"An identifier, not a quantity"
3,category_id,Identifier of the category the product belongs to,Whole number (ID),1487580005134238553,"An identifier, not a quantity"
4,category_code,Text label describing the product category or ...,Text (category),appliances.environment.vacuum,Many values are missing; periods separate cate...
5,brand,Brand associated with the product,Text (category),runail,Some values are missing
6,price,Recorded price of the product involved in the ...,Decimal number,2.62,Zero and negative values occur; retained for r...
7,user_id,Identifier of the user associated with the event,Whole number (ID),463240011,"An identifier, not a quantity"
8,user_session,Identifier for a browsing session,Text (ID),26dd6e6e-4dac-4778-8d2c-92e149dab885,Repeats across events in a session; missing va...

In [22]:
dictionary_file = cleaned_folder / "data_dictionary.csv"

data_dictionary.to_csv(dictionary_file, index=False)

print("Data dictionary saved to:", dictionary_file)

Data dictionary saved to: C:\Users\DELL\Desktop\Data Analytics\Project\Cleaned_Data\data_dictionary.csv